# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

knowledge panels:
    - '(kp|knowledge panels)'
    
folksonomy engine:
    - '(folksonomy engine)'
    
health card:
    - '(health card)'
    
summary card:
    - '(summary card)'

layout:
    - '(layout)'
    
database:
    - '(database)'
    
mlkit:
    - '(mlkit)'

android:
    - '(android)'
    
ios:
    - '(iphone|ipad|ios)'
    
scan:
    - '(scan)'
    
tests:
    - '(test)'
    
sentry:
    - '(sentry)'

matomo:
    - '(matomo)'

fastlane:
    - '(fastlane)'

darkmode:
    - '(darkmode|Dark mode)'

refactoring:
    - '(Refactoring)'
    
open beauty facts:
    - '(open beauty facts)'

# contribution, road to scores, knowledge panels, product page, scanning, settings, scan, help wanted, low priority, high priority, local cache
# onboarding, personal search, search, tag picker, category picker, image upload, photo upload, editing,  robotoff
# preferences, enhancement, ui/ux, launch, translations, summary card, screenshot-generation, personal scoring, performance, ingredients
# image carousel, history, ecoscore, category explorer, tests, speed, sentry, privacy, permissions, packaging input, open beauty facts
# offline, nutrition facts, mockups available, lists, gamification, folksonomy engine, dev mode, deeplinking, analytics, attributes, splashscree
# svg, security, ranking, health card, 
